# Generated by Django 3.0.7 on 2021-04-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='your_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
