# Generated by Django 3.2.1 on 2021-10-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210425_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='id',
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False),
        ),
    ]
